server:
  port: 8094

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/fullexDB
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/backprojectdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
  main:
    allow-bean-definition-overriding: true
  profiles:
    include:
      - open
      - oauth2

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:1234}
    listener:
      simple:
        auto-startup: true

rabbitmq:
  queue:
    name: ec2.queue
    notification: notification.queue
  exchange:
    name: ec2.exchange
  question:
    routing:
      key: ec2.routing.#
  notification:
    routing:
      key: ec2.notification.#

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

img:
  path:
    item: ${ITEM_UPLOAD_PATH:file:///E:/full/upload/backend/item/}
    board: ${BOARD_UPLOAD_PATH:file:///E:/full/upload/backend/board/}

with:
  host: ${{ secrets.EC2_HOST }}
  username: ${{ secrets.EC2_USERNAME }}
  key: ${{ secrets.EC2_SSH_KEY }}
  debug: true